goog.module('elemental2.dom.DomGlobal.$Overlay');

goog.require('nativebootstrap.Util');
goog.require('elemental2.core.JsArray.$Overlay');
goog.require('elemental2.core.Transferable.$Overlay');
goog.require('elemental2.dom.Blob.$Overlay');
goog.require('elemental2.dom.CanvasRenderingContext2D.$Overlay');
goog.require('elemental2.dom.Database.$Overlay');
goog.require('elemental2.dom.DatabaseCallback.$Overlay');
goog.require('elemental2.dom.DomGlobal.CreateImageBitmapImageUnionType.$Overlay');
goog.require('elemental2.dom.DomGlobal.CreateImageBitmapSxOrOptionsUnionType.$Overlay');
goog.require('elemental2.dom.DomGlobal.FetchInputUnionType.$Overlay');
goog.require('elemental2.dom.DomGlobal.ImportScriptsVar_argsUnionType.$Overlay');
goog.require('elemental2.dom.DomGlobal.OpenDatabaseCallbackUnionType.$Overlay');
goog.require('elemental2.dom.DomGlobal.PostMessageTargetOriginOrPortsOrTransferUnionType.$Overlay');
goog.require('elemental2.dom.DomGlobal.PostMessageTargetOriginOrTransferUnionType.$Overlay');
goog.require('elemental2.dom.DomGlobal.RequestIdleCallbackOptionsUnionType.$Overlay');
goog.require('elemental2.dom.DomGlobal.SetIntervalCallbackUnionType.$Overlay');
goog.require('elemental2.dom.DomGlobal.SetTimeoutCallbackUnionType.$Overlay');
goog.require('elemental2.dom.HTMLCanvasElement.$Overlay');
goog.require('elemental2.dom.HTMLDocument.$Overlay');
goog.require('elemental2.dom.HTMLImageElement.$Overlay');
goog.require('elemental2.dom.HTMLVideoElement.$Overlay');
goog.require('elemental2.dom.IdleCallbackOptions.$Overlay');
goog.require('elemental2.dom.IdleDeadline.$Overlay');
goog.require('elemental2.dom.ImageBitmap.$Overlay');
goog.require('elemental2.dom.ImageBitmapOptions.$Overlay');
goog.require('elemental2.dom.ImageData.$Overlay');
goog.require('elemental2.dom.Location.$Overlay');
goog.require('elemental2.dom.Navigator.$Overlay');
goog.require('elemental2.dom.Request.$Overlay');
goog.require('elemental2.dom.RequestInit.$Overlay');
goog.require('elemental2.dom.Response.$Overlay');
goog.require('elemental2.dom.Screen.$Overlay');
goog.require('elemental2.dom.TrustedScript.$Overlay');
goog.require('elemental2.dom.TrustedScriptURL.$Overlay');
goog.require('elemental2.dom.VisualViewport.$Overlay');
goog.require('elemental2.dom.Window.$Overlay');
goog.require('elemental2.promise.Promise.$Overlay');
goog.require('javaemul.internal.InternalPreconditions');
goog.require('jsinterop.base.Js');

const DomGlobal_$Overlay = goog.require('elemental2.dom.DomGlobal.$Overlay$impl');
exports = DomGlobal_$Overlay; 
