goog.module('org.gwtproject.dom.style.shared.Display');

goog.require('java.lang.Enum');
goog.require('nativebootstrap.Util');
goog.require('org.gwtproject.dom.style.shared.HasCssName');
goog.require('nativebootstrap.Equality');
goog.require('org.gwtproject.dom.style.shared.Display.$1');
goog.require('org.gwtproject.dom.style.shared.Display.$10');
goog.require('org.gwtproject.dom.style.shared.Display.$11');
goog.require('org.gwtproject.dom.style.shared.Display.$12');
goog.require('org.gwtproject.dom.style.shared.Display.$13');
goog.require('org.gwtproject.dom.style.shared.Display.$14');
goog.require('org.gwtproject.dom.style.shared.Display.$15');
goog.require('org.gwtproject.dom.style.shared.Display.$16');
goog.require('org.gwtproject.dom.style.shared.Display.$17');
goog.require('org.gwtproject.dom.style.shared.Display.$18');
goog.require('org.gwtproject.dom.style.shared.Display.$19');
goog.require('org.gwtproject.dom.style.shared.Display.$2');
goog.require('org.gwtproject.dom.style.shared.Display.$3');
goog.require('org.gwtproject.dom.style.shared.Display.$4');
goog.require('org.gwtproject.dom.style.shared.Display.$5');
goog.require('org.gwtproject.dom.style.shared.Display.$6');
goog.require('org.gwtproject.dom.style.shared.Display.$7');
goog.require('org.gwtproject.dom.style.shared.Display.$8');
goog.require('org.gwtproject.dom.style.shared.Display.$9');
goog.require('vmbootstrap.Arrays');
goog.require('vmbootstrap.Enums');

const Display = goog.require('org.gwtproject.dom.style.shared.Display$impl');
exports = Display; 
