goog.module('org.gwtproject.dom.client.Style.$Overlay');

goog.require('nativebootstrap.Util');
goog.require('elemental2.dom.CSSProperties.OpacityUnionType.$Overlay');
goog.require('elemental2.dom.CSSStyleDeclaration.$Overlay');
goog.require('java.lang.String');
goog.require('jsinterop.base.Js');
goog.require('jsinterop.base.JsPropertyMap.$Overlay');
goog.require('org.gwtproject.dom.style.shared.BorderStyle');
goog.require('org.gwtproject.dom.style.shared.Clear');
goog.require('org.gwtproject.dom.style.shared.CssProperty');
goog.require('org.gwtproject.dom.style.shared.Cursor');
goog.require('org.gwtproject.dom.style.shared.Display');
goog.require('org.gwtproject.dom.style.shared.Float');
goog.require('org.gwtproject.dom.style.shared.FontStyle');
goog.require('org.gwtproject.dom.style.shared.FontWeight');
goog.require('org.gwtproject.dom.style.shared.ListStyleType');
goog.require('org.gwtproject.dom.style.shared.OutlineStyle');
goog.require('org.gwtproject.dom.style.shared.Overflow');
goog.require('org.gwtproject.dom.style.shared.Position');
goog.require('org.gwtproject.dom.style.shared.TableLayout');
goog.require('org.gwtproject.dom.style.shared.TextAlign');
goog.require('org.gwtproject.dom.style.shared.TextDecoration');
goog.require('org.gwtproject.dom.style.shared.TextJustify');
goog.require('org.gwtproject.dom.style.shared.TextOverflow');
goog.require('org.gwtproject.dom.style.shared.TextTransform');
goog.require('org.gwtproject.dom.style.shared.Unit');
goog.require('org.gwtproject.dom.style.shared.VerticalAlign');
goog.require('org.gwtproject.dom.style.shared.Visibility');
goog.require('org.gwtproject.dom.style.shared.WhiteSpace');
goog.require('vmbootstrap.Asserts');
goog.require('vmbootstrap.Casts');

const Style_$Overlay = goog.require('org.gwtproject.dom.client.Style.$Overlay$impl');
exports = Style_$Overlay; 
