name: Publish API Documentation

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish-apidocs:
    name: Publish API Documentation
    runs-on: ubuntu-latest
    env:
      MVN: ./mvnw --show-version --batch-mode --no-transfer-progress
    steps:
      - uses: ts-graphviz/setup-graphviz@v2
      - uses: actions/checkout@v7
      - uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: temurin
          cache: maven
      - run: $MVN install
        working-directory: bom
      - run: $MVN install -Dquickly
      - run: $MVN depgraph:aggregate
      - run: |
          $MVN org.apache.maven.plugins:maven-antrun-plugin:run@copy-doc-files
          $MVN org.apache.maven.plugins:maven-antrun-plugin:run@copy-sources
          $MVN org.apache.maven.plugins:maven-antrun-plugin:run@copy-demos
          $MVN javadoc:javadoc
        working-directory: apidoc
      - name: Package and upload apidocs
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          cd apidoc/target/reports/apidocs
          zip -rq /tmp/apidocs.zip .
          LATEST_TAG=$(gh release list --limit 1 --json tagName --jq '.[0].tagName')
          gh release upload "$LATEST_TAG" /tmp/apidocs.zip --clobber
