name: GWT.com

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy-gwtcom:
    name: Deploy GWT.com Maven Artifacts
    runs-on: ubuntu-latest
    env:
      MVN: ./mvnw --show-version --batch-mode
    steps:
      - name: Get Version
        id: get-version
        uses: battila7/get-version-action@v2.3.0
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3
      - name: GWT.com
        id: gwtcom
        run: |
          ./versionBump.sh ${{ steps.get-version.outputs.version-without-v }}-gwtcom
          sed -n -f sed/pom.sed -i pom.xml
          sed -n -f sed/module.sed -i src/main/resources/org/jboss/elemento/Core.gwt.xml
          sed -n -f sed/import.sed -i src/main/java/org/jboss/elemento/Elements.java
          sed -n -f sed/import.sed -i src/main/java/org/jboss/elemento/EventType.java
          sed -n -f sed/import.sed -i src/main/java/org/jboss/elemento/HtmlContent.java
      - name: Results
        id: results
        run: |
          more pom.xml
