ignoredBuiltDependencies:
  - '@swc/core'
  - lmdb
  - msgpackr-extract

onlyBuiltDependencies:
  - '@parcel/watcher'

overrides:
  axios@>=1.0.0 <1.15.1: '>=1.15.1'
  axios@>=1.0.0 <1.15.2: '>=1.15.2'
  follow-redirects@<=1.15.11: '>=1.16.0'
